name: notes_app
description: Pretty simple app for notes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  
  intl: ^0.17.0

  # Service Locator
  get_it: ^7.2.0
  
  # Database
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # BLoC
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1

  # Code gen
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0

  # Widgets
  swipeable_tile: ^0.0.2

  # Value equality
  equatable: ^2.0.3

  # Functional programming
  dartz: ^0.10.0

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4
  hive_generator: ^1.1.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true